name: Set version (npm)
description: "Set version (npm)"

inputs:
  next_version:
    description: "next version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch node version
      shell: bash
      working-directory: web
      run: |
        node_version=$(cat package.json | jq -r '.volta.node')
        echo "node_version=${node_version}" >> $GITHUB_ENV

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}

    - name: Cache for npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: cache-npm-v1-web-${{ hashFiles('web/package-lock.json') }}
        restore-keys: |
          cache-npm-v1-web-
          cache-npm-v1-

    - name: Set next version
      shell: bash
      working-directory: web
      run: |
        npm version ${{ inputs.next_version }} --no-git-tag-version
