name: Create PR for release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create-pr-for-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Read current version
        id: current_version
        run: |
          echo "version=$(./gradlew printCurrentVersion -q)" >> $GITHUB_OUTPUT

      - name: Release version
        id: release_version
        run: |
          ./gradlew versioning -Paction=remove-modifier
          echo "version=$(./gradlew printCurrentVersion -q)" >> $GITHUB_OUTPUT

      - name: Create branch
        id: create_branch
        run: |
          BRANCH_NAME=release/${{ steps.release_version.outputs.version }}
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: RC version
        id: rc_version
        run: |
          ./gradlew versioning -Paction=append-modifier -Pmodifier=RC
          echo "version=$(./gradlew printCurrentVersion -q)" >> $GITHUB_OUTPUT

      - name: Commit and push
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add --all
          git commit -m "Set version to ${{ steps.rc_version.outputs.version }}"
          git push origin ${{ steps.create_branch.outputs.branch_name }}

      - name: Create pull request
        run: |
          gh pr create \
            --title "release: ${{ steps.next_version.outputs.version }}" \
            --body-file .github/pull_request_template.md \
            --base main \
            --head ${{ steps.create_branch.outputs.branch_name }} \
            --assignee ${{ github.actor }}
            # TODO: --draft
          # TODO: release template?
