name: Create release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: read

jobs:
  create-release:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Release version
        id: release_version
        run: |
          echo "version=$(./gradlew printCurrentVersion -q)" >> $GITHUB_OUTPUT

      - name: Create release
        run: |
          gh release create \
            --title "v${{ steps.release_version.outputs.version }}" \
            --target ${{ github.ref_name }} \
            --generate-notes \
            --prerelease \
            v${{ steps.release_version.outputs.version }}

  run-release:
    needs: create-release
    uses: ./.github/workflows/release.yml
