name: Create PR for release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create-pr-for-release:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Validate
        run: |
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "This workflow support 'main' branch only."
            exit 1
          fi

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Change version
        id: versioning
        uses: ./.github/actions/versioning/change-version
        with:
          action: "not increment"
          modifier: "RC"

      - name: Preparation for git operation
        id: preparation_for_git_operation
        run: |
          echo "branch_name=release/${{ steps.versioning.outputs.release_version }}" >> $GITHUB_OUTPUT
          echo "commit_message=Set version to ${{ steps.versioning.outputs.next_version }}" >> $GITHUB_OUTPUT
          echo "pr_title=Preparation for release: ${{ steps.versioning.outputs.release_version }}" >> $GITHUB_OUTPUT

      - name: Git operation
        uses: ./.github/actions/versioning/git-operation
        with:
          branch_name: ${{ steps.preparation_for_git_operation.outputs.branch_name }}
          commit_message: ${{ steps.preparation_for_git_operation.outputs.commit_message }}

      - name: Create pull request
        id: create_pull_request
        uses: ./.github/actions/versioning/create-draft-pull-request
        env:
          PR_TITLE: ${{ steps.preparation_for_git_operation.outputs.pr_title }}
        with:
          base_branch: ${{ github.ref_name }}
          head_branch: ${{ steps.preparation_for_git_operation.outputs.branch_name }}
          title: $PR_TITLE
          label: "release"
          reviewer: ${{ vars.PR_REVIEWERS_CSV }}
          body_file: .github/pull_request_template_for_release.md

      - name: Output summary
        env:
          PR_TITLE: ${{ steps.preparation_for_git_operation.outputs.pr_title }}
        run: |
          echo "## Created pull request" >> $GITHUB_STEP_SUMMARY
          echo "[${PR_TITLE}](${{ steps.create_pull_request.outputs.url }})" >> $GITHUB_STEP_SUMMARY
          echo "- base branch: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- head branch: \`${{ steps.preparation_for_git_operation.outputs.branch_name }}\`" >> $GITHUB_STEP_SUMMARY
