name: Create PR for versioning

on:
  workflow_dispatch:
    inputs:
      action:
        description: "action"
        required: true
        type: choice
        options:
          - ""
          - "major version up"
          - "minor version up"
          - "patch version up"
          - "not increment"
      modifier:
        description: "version modifier"
        required: true
        type: choice
        options:
          - "SNAPSHOT"
          - "RC"
          - "( none )"

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create-pr-for-versioning:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Change version
        id: versioning
        uses: ./.github/actions/versioning/change-version
        with:
          action: ${{ github.event.inputs.action  }}
          modifier: ${{ github.event.inputs.modifier }}

      - name: Preparation for git operation
        id: preparation_for_git_operation
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "branch_name=version-to-${{ steps.versioning.outputs.next_version }}_${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "commit_message=Set version to ${{ steps.versioning.outputs.next_version }}" >> $GITHUB_OUTPUT
          echo "pr_title=Versioning: ${{ steps.versioning.outputs.next_version }}" >> $GITHUB_OUTPUT
          echo "pr_body=Change version \`${{ steps.versioning.outputs.current_version }}\` to \`${{ steps.versioning.outputs.next_version }}\`." >> $GITHUB_OUTPUT

      - name: Git operation
        id: git-operation
        uses: ./.github/actions/versioning/git-operation
        with:
          branch_name: ${{ steps.preparation_for_git_operation.outputs.branch_name }}
          commit_message: ${{ steps.preparation_for_git_operation.outputs.commit_message }}

      - name: Create pull request
        id: create_pull_request
        uses: ./.github/actions/versioning/create-draft-pull-request
        with:
          base_branch: ${{ github.ref_name }}
          head_branch: ${{ steps.preparation_for_git_operation.outputs.branch_name }}
          title: "${{ steps.preparation_for_git_operation.outputs.pr_title }}"
          label: "versioning"
          reviewer: "katoys"
          body: "${{ steps.preparation_for_git_operation.outputs.pr_body }}"

      - name: Output summary
        run: |
          echo "- ${{ steps.preparation_for_git_operation.outputs.pr_body }}" >> $GITHUB_STEP_SUMMARY
          echo "- Created pull request: ${{ steps.versioning.outputs.next_version }}" >> $GITHUB_STEP_SUMMARY
          echo "  - base branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "  - head branch: ${{ steps.preparation_for_git_operation.outputs.branch_name }}" >> $GITHUB_STEP_SUMMARY
