name: Create PR for release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create-pr-for-release:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Versioning for gradle (remove SNAPSHOT)
        id: release_versioning
        uses: ./.github/actions/versioning/versioning-for-gradle
        with:
          action: "not increment"
          modifier: "( none )"

      - name: Versioning for gradle (appned RC)
        id: versioning
        uses: ./.github/actions/versioning/versioning-for-gradle
        with:
          action: "not increment"
          modifier: RC

      - name: Versioning for npm
        uses: ./.github/actions/versioning/versioning-for-npm
        with:
          next_version: ${{ steps.versioning.outputs.next_version }}

      - name: Preparation for git operation
        id: preparation_for_git_operation
        run: |
          echo "branch_name=release/${{ steps.release_versioning.outputs.next_version }}" >> $GITHUB_OUTPUT
          echo "commit_message=Set version to ${{ steps.versioning.outputs.next_version }}" >> $GITHUB_OUTPUT

      - name: Git operation
        id: git-operation
        uses: ./.github/actions/versioning/git-operation
        with:
          branch_name: ${{ steps.preparation_for_git_operation.outputs.branch_name }}
          commit_message: ${{ steps.preparation_for_git_operation.outputs.commit_message }}

      - name: Create pull request
        run: |
          gh pr create \
            --title "Preparation for release: ${{ steps.release_versioning.outputs.next_version }}" \
            --body-file .github/pull_request_template_for_release.md \
            --base main \
            --head ${{ steps.git-operation.outputs.branch_name }} \
            --label "release" \
            --assignee ${{ github.actor }} \
            --reviewer katoys \
            --draft
