name: Set version (hotfix flow)

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: "action type"
        required: true
        type: choice
        options:
          - ""
          - "up patch with snapshot"
          - "remove snapshot"

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  set-version:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Read current version
        id: current_version
        run: |
          echo "version=$(./gradlew printCurrentVersion -q)" >> $GITHUB_OUTPUT

      - name: Next version
        id: next_version
        run: |
          case "${{ github.event.inputs.action_type }}" in
            "up patch with snapshot")
              ./gradlew versioning -Paction=up-patch;;
            "remove snapshot")
              ./gradlew versioning -Paction=remove-modifier -q;;
            *)
              echo "Invalid action type: ${{ github.event.inputs.action_type }}"
              exit 1;;
          esac
          echo "version=$(./gradlew printCurrentVersion -q)" >> $GITHUB_OUTPUT

      - name: Create branch
        id: create_branch
        run: |
          BRANCH_NAME=set-version-to-${{ steps.next_version.outputs.version }}
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      
      - name: Commit and push
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add --all
          git commit -m "Set version to ${{ steps.next_version.outputs.version }}"
          git push origin ${{ steps.create_branch.outputs.branch_name }}

      - name: Create pull request
        run: |
          gh pr create \
            --title "Versioning: ${{ steps.next_version.outputs.version }}" \
            --body "Change version \`${{ steps.current_version.outputs.version }}\` to \`${{ steps.next_version.outputs.version }}\`. by @${{ github.actor }}\n\ncf https://sms-kaipoke.esa.io/posts/18939" \
            --base ${{ github.ref_name }} \
            --head ${{ steps.create_branch.outputs.branch_name }} \
            --label "versioning" \
            --assignee ${{ github.actor }} \
            --reviewer katoys
