name: Next version (standard flow)

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "base branch"
        required: true
        type: string
      action_type:
        description: "action type"
        required: true
        type: choice
        options:
          - ""
          - "up major with snapshot"
          - "up minor with snapshot"
          - "up patch"
          - "remove snapshot"

jobs:
  to-next-version:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Read version
        id: read_version
        run: |
          echo "version=$(./gradlew printCurrentVersion -q)" >> $GITHUB_OUTPUT

      - name: Add comment
        run: |
          gh issue comment "https://github.com/katoys/workflow-sample/issues/1" --body "${{ steps.read_version.outputs.version }}"
