name: Release

on:
  push:
    tags:
      - '**'
  workflow_call:
    inputs:
      tag_name:
        required: false
        type: string

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  show-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "gradle"

      - name: Read current version
        run: |
          ./gradlew printCurrentVersion -q | tail -1

      - name: Show tag
        run: |
          echo "from GITHU_REF : '${GITHUB_REF#refs/*/}'"
          echo "from inputs    : '${{ inputs.tag_name }}'"
